version: 2.1
# orbs:
#   node: circleci/node@5.0.1

# Define a common Docker container and environment for jobs
executors:
  docker-publisher:
    # Define the image tag
    environment:
      IMAGE_TAG: goodwill80/helloworld:latest
    # Use `docker:stable` as the Docker image for this executor
    docker:
      - image: cimg/node:16.10

jobs:
  build:
    executor: docker-publisher
    # docker:
    #   - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: |
          echo "Installing dependencies..."
          npm install
  test:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: |
          echo "Running tests..."
          npm run test

workflows:
  simple_workflow:
    jobs:
      - build
      - test:
          requires:
            - build
